### ISSUE TITLE
[Development Discussion] Moderators System

### ISSUE THREAD

**Issue by gktown** [memeit-lol/memeit.lol#9]
1) When a post is created push it to steemit.com and pending category.
2) Only moderators can access pending posts, and they will verify posts that are a genuine / humorous use of the meme.
3) We'll use this to filter/hide and discourage automated/worthless content.
4) When multiple moderators request an image to be hidden, we'll hide it from Steemit.lol and it will no longer be eligible for bot vote.
5) If moderators hide enough of your posts, you'll get limited on how much you can contribute.
6) When a moderator upvotes a post, it gets published.

Published posts get attention from the Steemit.lol vote bot :smile:

**Comment by gktown** [comment]
**Moderator Reward System**
We've allocated 3% of post rewards to go to Moderators. Moderators help to decide what gets published on the site via voting with their steempower, so the 3% reward will be a booster to make it more profitable to check out memes in your spare time.

**Comment by Rishi556** [comment]
I'll fill out the form to be a moderator when they open up.

**Comment by ms10398** [comment]
I would also like to be a moderator on it

Just as the website is up

Excited for it
